const GET_USER_TYPE = {
    BANNED: 0,
    AVAILABLE: 1,
    ALL: 2
}

const FRIEND_STATUS = {
    NOTHING: 0,
    SEND_REQUEST: 1,
    RECEIVE_REQUEST: 2,
    FRIENDED: 3,
}

const REQUEST_TYPE = {
    UNFRIEND: 0,
    BLOCK: 1,
    UNBLOCK: 2,
    FRIEND_REQUEST: 3
}

const ACCOUNT_TYPE = {
    PUBLIC: 0,
    PRIVATE: 1
}

const CHANNEL_TYPE = {
    CHAT: 0,
    VOICE: 1
}

module.exports = { GET_USER_TYPE, FRIEND_STATUS, REQUEST_TYPE, ACCOUNT_TYPE, CHANNEL_TYPE };